export const GET_DOCTOR_LIST_REQUEST = "GET_DOCTOR_LIST_REQUEST";
export const GET_DOCTOR_LIST_SUCCESS = "GET_DOCTOR_LIST_SUCCESS";
export const GET_DOCTOR_LIST_FAILED  = "GET_DOCTOR_LIST_FAILED";
export const GET_PATIENT_SIGN_UP_REQUEST = "GET_PATIENT_SIGN_UP_REQUEST";
export const GET_PATIENT_SIGN_UP_SUCCESS = "GET_PATIENT_SIGN_UP_SUCCESS";
export const GET_PATIENT_SIGN_UP_FAILED = "GET_PATIENT_SIGN_UP_FAILED";
export const GET_DOCTOR_SIGN_UP_REQUEST = "GET_DOCTOR_SIGN_UP_REQUEST";
export const GET_DOCTOR_SIGN_UP_SUCCESS = "GET_DOCTOR_SIGN_UP_SUCCESS";
export const GET_DOCTOR_SIGN_UP_FAILED = "GET_DOCTOR_SIGN_UP_FAILED";
export const GET_USER_SIGN_IN_REQUEST = "GET_USER_SIGN_IN_REQUEST";
export const GET_USER_SIGN_IN_SUCCESS = "GET_USER_SIGN_IN_SUCCESS";
export const GET_USER_SIGN_IN_FAILED = "GET_USER_SIGN_IN_FAILED";


